-- Migration 0011: add more internship sources (Greenhouse + Lever)

-- ── Global Tech — Greenhouse ────────────────────────────────────────────────
INSERT OR IGNORE INTO sources (ats_type, token, label) VALUES
  ('greenhouse', 'hubspot',       'HubSpot'),
  ('greenhouse', 'canva',         'Canva'),
  ('greenhouse', 'palantir',      'Palantir'),
  ('greenhouse', 'asana',         'Asana'),
  ('greenhouse', 'zendesk',       'Zendesk'),
  ('greenhouse', 'cloudflare',    'Cloudflare'),
  ('greenhouse', 'datadog',       'Datadog'),
  ('greenhouse', 'pagerduty',     'PagerDuty'),
  ('greenhouse', 'hashicorp',     'HashiCorp'),
  ('greenhouse', 'mongodb',       'MongoDB'),
  ('greenhouse', 'elastic',       'Elastic'),
  ('greenhouse', 'gitlab',        'GitLab'),
  ('greenhouse', 'okta',          'Okta'),
  ('greenhouse', 'twilio',        'Twilio'),
  ('greenhouse', 'sendgrid',      'SendGrid'),
  ('greenhouse', 'segment',       'Segment'),
  ('greenhouse', 'mixpanel',      'Mixpanel'),
  ('greenhouse', 'amplitude',     'Amplitude'),
  ('greenhouse', 'intercom',      'Intercom'),
  ('greenhouse', 'airtable',      'Airtable'),
  ('greenhouse', 'coda',          'Coda'),
  ('greenhouse', 'retool',        'Retool'),
  ('greenhouse', 'vercel',        'Vercel'),
  ('greenhouse', 'supabase',      'Supabase'),
  ('greenhouse', 'rippling',      'Rippling'),
  ('greenhouse', 'gusto',         'Gusto'),
  ('greenhouse', 'doordash',      'DoorDash'),
  ('greenhouse', 'lyft',          'Lyft'),
  ('greenhouse', 'waymo',         'Waymo'),
  ('greenhouse', 'scale',         'Scale AI'),
  ('greenhouse', 'openai',        'OpenAI'),
  ('greenhouse', 'huggingface',   'Hugging Face'),
  ('greenhouse', 'mistral',       'Mistral AI'),
  ('greenhouse', 'together',      'Together AI'),
  ('greenhouse', 'modal',         'Modal Labs'),
  ('greenhouse', 'replit',        'Replit'),
  ('greenhouse', 'linear',        'Linear'),
  ('greenhouse', 'loom',          'Loom'),
  ('greenhouse', 'miro',          'Miro'),
  ('greenhouse', 'webflow',       'Webflow'),
  ('greenhouse', 'zapier',        'Zapier'),
  ('greenhouse', 'calendly',      'Calendly'),
  ('greenhouse', 'typeform',      'Typeform'),
  ('greenhouse', 'attentive',     'Attentive'),
  ('greenhouse', 'benchling',     'Benchling'),
  ('greenhouse', 'palantir',      'Palantir'),
  ('greenhouse', 'unity',         'Unity Technologies'),
  ('greenhouse', 'epic',          'Epic Games'),
  ('greenhouse', 'riotgames',     'Riot Games'),
  ('greenhouse', 'spotify',       'Spotify');

-- ── Global Tech — Lever ─────────────────────────────────────────────────────
INSERT OR IGNORE INTO sources (ats_type, token, label) VALUES
  ('lever', 'stripe',         'Stripe'),
  ('lever', 'figma',          'Figma Inc'),
  ('lever', 'carta',          'Carta'),
  ('lever', 'lattice',        'Lattice'),
  ('lever', 'watershed',      'Watershed'),
  ('lever', 'benchmarkEmail', 'Benchmark Email'),
  ('lever', 'ironclad',       'Ironclad'),
  ('lever', 'verkada',        'Verkada'),
  ('lever', 'anduril',        'Anduril Industries'),
  ('lever', 'shield-ai',      'Shield AI'),
  ('lever', 'samsara',        'Samsara'),
  ('lever', 'instabase',      'Instabase'),
  ('lever', 'retool',         'Retool'),
  ('lever', 'dbt-labs',       'dbt Labs'),
  ('lever', 'hightouch',      'Hightouch'),
  ('lever', 'census',         'Census'),
  ('lever', 'hex',            'Hex'),
  ('lever', 'mode',           'Mode Analytics'),
  ('lever', 'preset',         'Preset'),
  ('lever', 'atlan',          'Atlan');
